name: Check PR
permissions:
  contents: read

on:
  pull_request:
    branches: [main] # Triggers only for PRs targeting the 'main' branch


jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set Up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 17
          distribution: oracle

      - name: Set Up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Run Tests
        run: |
          flutter test

      - name: Analyze Lints
        run: |
          flutter analyze

      - name: Build Debug APK (no signing keys required)
        run: |
          flutter build apk --debug
